### PR TITLE
Add build infrastructure from the PPA packages

### PR DESCRIPTION
**Pull request by skitt**
This integrates the build infrastructure as used in the PPA packages,
with a few changes: all the test files are moved to tests, and
README.md is shipped as the documentation and adjusted to match these
changes.

This enables other autoconf niceties such as make dist.

Signed-off-by: Stephen Kitt <steve@sk2.org>

### CODE REVIEW

**Comment by circulosmeos** [comment]
Thanks for the pull, @skitt 
Couldn't the man page be also integrated with these changes?

**Comment by skitt** [comment]
> Thanks for the pull, @skitt
> Couldn't the man page be also integrated with these changes?

Good point, I’d missed that. I’ve added the manpage, and simplified the changes a little. Hopefully this keeps the repository simple enough for your liking, while providing all the nice added features of the PPA packages for everyone (including not only Debian, but other distributions such as Fedora).

**Comment by circulosmeos** [comment]
Thanks @skitt ,
hope this will ease packaging!

**Comment by skitt** [comment]
> Thanks @skitt ,
> hope this will ease packaging!

It will indeed, thanks for merging!

**Pull request merged**
